---

- name: Mongo Install Test
  hosts: localhost
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
  roles:
   - { role: base, tags: [ 'base' ] }
   - { role: install, tags: [ 'install' ] }
   - { role: user, tags: [ 'user' ] }

#  tasks: 
